name: Unit tests

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }} and Jest v${{ matrix.jest-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
        jest-version: [27, 28, 29]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: install with jest v${{ matrix.jest-version }}
        run: pnpm add --save-dev jest@${{ matrix.jest-version }} babel-jest@${{ matrix.jest-version }}
      - name: run tests
        run: pnpm test
  test-os:
    name: Test on ${{ matrix.os }} using Node.js 22
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: run tests
        run: pnpm test
